
package org.folio.rest.client;

import io.vertx.core.Handler;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.HttpClientResponse;
import org.folio.rest.tools.utils.VertxUtils;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;


/**
 * Auto-generated code - based on class org.folio.rest.jaxrs.resource.SourceStorageRecords
 *
 */
public class SourceStorageRecordsClient {

    private final static String GLOBAL_PATH = "/source-storage/records";
    private String tenantId;
    private String token;
    private String okapiUrl;
    private HttpClientOptions options;
    private HttpClient httpClient;

    public SourceStorageRecordsClient(String okapiUrl, String tenantId, String token, boolean keepAlive, int connTO, int idleTO) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this.tenantId = tenantId;
        this.token = token;
        this.okapiUrl = okapiUrl;
        options = new HttpClientOptions();
        options.setLogActivity(true);
        options.setKeepAlive(keepAlive);
        options.setConnectTimeout(connTO);
        options.setIdleTimeout(idleTO);
        httpClient = VertxUtils.getVertxFromContextOrNew().createHttpClient(options);
    }

    public SourceStorageRecordsClient(String okapiUrl, String tenantId, String token, boolean keepAlive) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this(okapiUrl, tenantId, token, keepAlive, 2000, 5000);
    }

    public SourceStorageRecordsClient(String okapiUrl, String tenantId, String token) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this(okapiUrl, tenantId, token, true, 2000, 5000);
    }

    /**
     * @deprecated  use a constructor that takes a full okapiUrl instead
     *
     */
    @Deprecated
    public SourceStorageRecordsClient(String host, int port, String tenantId, String token, boolean keepAlive, int connTO, int idleTO) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this(((("http://"+ host)+":")+ port), tenantId, token, keepAlive, connTO, idleTO);
    }

    /**
     * @deprecated  use a constructor that takes a full okapiUrl instead
     *
     */
    @Deprecated
    public SourceStorageRecordsClient(String host, int port, String tenantId, String token, boolean keepAlive) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this(host, port, tenantId, token, keepAlive, 2000, 5000);
    }

    /**
     * @deprecated  use a constructor that takes a full okapiUrl instead
     *
     */
    @Deprecated
    public SourceStorageRecordsClient(String host, int port, String tenantId, String token) {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this(host, port, tenantId, token, true, 2000, 5000);
    }

    /**
     * Convenience constructor for tests ONLY!<br>Connect to localhost on 8081 as folio_demo tenant.@deprecated  use a constructor that takes a full okapiUrl instead
     *
     */
    @Deprecated
    public SourceStorageRecordsClient() {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        this("localhost", 8081, "folio_demo", "folio_demo", false, 2000, 5000);
    }

    /**
     * Service endpoint "/source-storage/records/"+id+""+queryParams.toString()
     *
     */
    public void deleteSourceStorageRecordsById(String id, String lang, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (lang!= null) {
            queryParams.append("lang=");
            queryParams.append(URLEncoder.encode(lang, "UTF-8"));
            queryParams.append("&");
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.deleteAbs(okapiUrl+"/source-storage/records/"+id+""+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Accept", "text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+queryParams.toString()
     *
     */
    public void getSourceStorageRecords(String snapshotId, String state, String[] orderBy, int offset, int limit, String lang, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (snapshotId!= null) {
            queryParams.append("snapshotId=");
            queryParams.append(URLEncoder.encode(snapshotId, "UTF-8"));
            queryParams.append("&");
        }
        if (state!= null) {
            queryParams.append("state=");
            queryParams.append(URLEncoder.encode(state, "UTF-8"));
            queryParams.append("&");
        }
        if (orderBy!= null) {
            queryParams.append("orderBy=");
            if(orderBy.getClass().isArray()){queryParams.append(String.join("&orderBy=",orderBy));}
            queryParams.append("&");
        }
        queryParams.append("offset=");
        queryParams.append(offset);
        queryParams.append("&");
        queryParams.append("limit=");
        queryParams.append(limit);
        queryParams.append("&");
        if (lang!= null) {
            queryParams.append("lang=");
            queryParams.append(URLEncoder.encode(lang, "UTF-8"));
            queryParams.append("&");
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.getAbs(okapiUrl+"/source-storage/records/"+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+id+""+queryParams.toString()
     *
     */
    public void getSourceStorageRecordsById(String id, String lang, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (lang!= null) {
            queryParams.append("lang=");
            queryParams.append(URLEncoder.encode(lang, "UTF-8"));
            queryParams.append("&");
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.getAbs(okapiUrl+"/source-storage/records/"+id+""+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+id+"/formatted"+queryParams.toString()
     *
     */
    public void getSourceStorageRecordsFormattedById(String id, String idType, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (idType!= null) {
            queryParams.append("idType=");
            queryParams.append(URLEncoder.encode(idType, "UTF-8"));
            queryParams.append("&");
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.getAbs(okapiUrl+"/source-storage/records/"+id+"/formatted"+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+queryParams.toString()
     *
     */
    public void postSourceStorageRecords(String lang, org.folio.rest.jaxrs.model.Record Record, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException, Exception
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (lang!= null) {
            queryParams.append("lang=");
            queryParams.append(URLEncoder.encode(lang, "UTF-8"));
            queryParams.append("&");
        }
        Buffer buffer = Buffer.buffer();
        if (Record!= null) {
            buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(Record));
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.postAbs(okapiUrl+"/source-storage/records/"+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Content-type", "application/json");
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.putHeader("Content-Length", buffer.length()+"");
        request.setChunked(true);
        request.write(buffer);
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+id+""+queryParams.toString()
     *
     */
    public void putSourceStorageRecordsById(String id, String lang, org.folio.rest.jaxrs.model.Record Record, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException, Exception
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (lang!= null) {
            queryParams.append("lang=");
            queryParams.append(URLEncoder.encode(lang, "UTF-8"));
            queryParams.append("&");
        }
        Buffer buffer = Buffer.buffer();
        if (Record!= null) {
            buffer.appendString(org.folio.rest.tools.ClientHelpers.pojo2json(Record));
        }
        io.vertx.core.http.HttpClientRequest request = httpClient.putAbs(okapiUrl+"/source-storage/records/"+id+""+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Content-type", "application/json");
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.putHeader("Content-Length", buffer.length()+"");
        request.setChunked(true);
        request.write(buffer);
        request.end();
    }

    /**
     * Service endpoint "/source-storage/records/"+id+"/suppress-from-discovery"+queryParams.toString()
     *
     */
    public void putSourceStorageRecordsSuppressFromDiscoveryById(String id, String idType, boolean suppress, Handler<HttpClientResponse> responseHandler)
        throws UnsupportedEncodingException
    {
        // Auto-generated code
        // - generated by       org.folio.rest.tools.ClientGenerator
        // - generated based on org.folio.rest.jaxrs.resource.SourceStorageRecordsResource
        StringBuilder queryParams = new StringBuilder("?");
        if (idType!= null) {
            queryParams.append("idType=");
            queryParams.append(URLEncoder.encode(idType, "UTF-8"));
            queryParams.append("&");
        }
        queryParams.append("suppress=");
        queryParams.append(suppress);
        queryParams.append("&");
        io.vertx.core.http.HttpClientRequest request = httpClient.putAbs(okapiUrl+"/source-storage/records/"+id+"/suppress-from-discovery"+queryParams.toString());
        request.handler(responseHandler);
        request.putHeader("Accept", "application/json,text/plain");
        if (tenantId!= null) {
            request.putHeader("X-Okapi-Token", token);
            request.putHeader("x-okapi-tenant", tenantId);
        }
        if (okapiUrl!= null) {
            request.putHeader("X-Okapi-Url", okapiUrl);
        }
        request.end();
    }

}
