FROM postgres:latest

ARG USER_HOME_DIR="/home/postgres"

RUN deluser postgres
RUN adduser postgres
RUN chown postgres:postgres $USER_HOME_DIR -R
RUN chown postgres:postgres /var/lib/postgresql -R

RUN apt-get update -y
RUN apt-get install -y default-jre-headless maven git

USER postgres
CMD ["postgres"]
