#%RAML 1.0

title: Source Record Storage Module
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage API
    content: API for managing records

types:
  snapshot: !include raml-storage/schemas/mod-source-record-storage/snapshot.json
  snapshotCollection: !include raml-storage/schemas/mod-source-record-storage/snapshotCollection.json
  record: !include raml-storage/schemas/dto/record.json
  recordCollection: !include raml-storage/schemas/dto/recordCollection.json
  result: !include raml-storage/schemas/dto/result.json
  resultCollection: !include raml-storage/schemas/dto/resultCollection.json
  errors: !include raml-storage/raml-util/schemas/errors.schema
  recordModel: !include raml-storage/schemas/mod-source-record-storage/recordModel.json

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml
  searchable: !include raml-storage/raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-storage/raml-util/rtypes/collection.raml
  collection-item: !include raml-storage/raml-util/rtypes/item-collection.raml

/source-storage:
  /snapshot:
    displayName: Snapshot
    description: API for managing Snapshots
    type:
      collection:
        schemaCollection: snapshotCollection
        schemaItem: snapshot
        exampleCollection: !include raml-storage/examples/mod-source-record-storage/snapshotCollection.sample
        exampleItem: !include raml-storage/examples/mod-source-record-storage/snapshot.sample
    get:
      description: Get a list of snapshots
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example status=NEW",
          example:
            "status=NEW"
        },
        pageable,
        validate
      ]
      responses:
        200:
          body:
            application/json:
              type: snapshotCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    post:
      description: "Create new snapshot"
      is: [validate]
      body:
        application/json:
          type: snapshot
      responses:
        201:
          body:
            application/json:
              type: snapshot
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{jobExecutionId}:
      get:
        description: Get snapshot by id
        responses:
          200:
            body:
              application/json:
                type: snapshot
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      put:
        description: Update snapshot
        body:
          application/json:
            type: snapshot
        responses:
          200:
            body:
              application/json:
                type: snapshot
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          422:
            description: "Unprocessable Entity"
            body:
              application/json:
                type: errors
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      delete:
        description: Delete snapshot by id
        responses:
          204:
            body:
              text/plain: !!null
          404:
            description: "File not found"
            body:
              text/plain:
                example: "File not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /record:
    displayName: Record
    description: API for managing Records
    type:
      collection:
        schemaCollection: recordCollection
        schemaItem: record
        exampleCollection: !include raml-storage/examples/mod-source-record-storage/recordCollection.sample
        exampleItem: !include raml-storage/examples/mod-source-record-storage/record.sample
    get:
      description: Get a list of records
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example recordType=MARC",
          example:
            "recordType=MARC"
        },
        pageable,
        validate
      ]
      responses:
        200:
          body:
            application/json:
              type: recordCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    post:
      description: "Create new record"
      is: [validate]
      body:
        application/json:
          type: record
      responses:
        201:
          body:
            application/json:
              type: record
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{id}:
      get:
        description: Get record by id
        responses:
          200:
            body:
              application/json:
                type: record
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      put:
        description: Update record
        body:
          application/json:
            type: record
        responses:
          200:
            body:
              application/json:
                type: record
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          422:
            description: "Unprocessable Entity"
            body:
              application/json:
                type: errors
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      delete:
        description: Delete record by id
        responses:
          204:
            body:
              text/plain: !!null
          404:
            description: "File not found"
            body:
              text/plain:
                example: "File not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /result:
    displayName: Result
    description: API for getting Results
    get:
      description: Get a list of results
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example recordType=MARC",
          example:
            "recordType=MARC"
        },
        pageable,
        validate
      ]
      responses:
        200:
          body:
            application/json:
              type: resultCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
