#%RAML 1.0

title: Source Record Storage Batch API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage Batch API
    content: Batch API for managing records

types:
  recordCollection: !include raml-storage/schemas/dto/recordCollection.json
  recordsBatchResponse: !include raml-storage/schemas/dto/recordsBatchResponse.json
  parsedRecordsBatchResponse: !include raml-storage/schemas/dto/parsedRecordsBatchResponse.json
  errors: !include raml-storage/raml-util/schemas/errors.schema
  marcBibCollection: !include marcBibCollection.json

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml

/source-storage/batch:
  /verify:
     displayName: Verify Marc Holdings Records 004 field
     description: Verify Marc Holdings Records 004 field
     post:
       description: Get a list of invalid Marc Bib Record IDs, which doesn't exists in the system
       is: [validate]
       body:
         application/json:
           description: List of Marc Bib Record IDs
           type: string[]
       responses:
         200:
           body:
             application/json:
               type: marcBibCollection
         400:
           description: Bad request
           body:
             text/plain:
               example: "Bad request"
         500:
           description: Internal server error
           body:
             text/plain:
               example: "Internal server error"
  /records:
    post:
      description: "Creates records from a record collection. It returns both saved records and error messages for records that were not saved."
      is: [validate]
      body:
        application/json:
          type: recordCollection
      responses:
        201:
          body:
            application/json:
              type: recordsBatchResponse
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
            application/json:
              type: recordsBatchResponse
  /parsed-records:
    put:
      description: "Updates parsed records from a collection. It returns both updated records and error messages for records that were not updated."
      is: [validate]
      body:
        application/json:
          type: recordCollection
      responses:
        200:
          body:
            application/json:
              type: parsedRecordsBatchResponse
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
            application/json:
              type: parsedRecordsBatchResponse
