#%RAML 1.0

title: Source Record Storage Stream API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage Stream API
    content: Streaming API for searching records

types:
  errors: !include raml-storage/raml-util/schemas/errors.schema

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml

/source-storage/stream:
  /records:
    displayName: Records Stream
    description: Stream collection of records
    get:
      is: [
        pageable,
        validate
      ]
      queryParameters:
        snapshotId:
          description: Filter by Snapshot Id
          type: string
          example: "e5ddbbdc-90b3-498f-bb8f-49367ca4c142"
          required: false
        state:
          description: Filter by State
          type: string
          example: "ACTUAL"
          required: false
        orderBy:
          description: Sort Records
          type: string[]
          example: ["order,ASC"]
          required: false
