#%RAML 1.0

title: Source Record Storage Event Handlers API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage Event Handlers API
    content: API for event handling

types:
  errors: !include raml-storage/raml-util/schemas/errors.schema
  dataImportEventPayload: !include raml-storage/schemas/common/dataImportEventPayload.json
  entityType: !include raml-storage/schemas/mod-data-import-converter-storage/entityType.json
  dataImportEventTypes: !include raml-storage/schemas/common/dataImportEventTypes.json
  parsedRecordDto: !include raml-storage/schemas/dto/parsedRecordDto.json
  data: !include raml-storage/schemas/mod-data-import-converter-storage/mapping-profile-detail/marcData.json

/source-storage/handlers:
  /data-import:
    description: "Handler for data import process events"
    post:
      body:
        application/json:
          type: string
      responses:
        204:
  /updated-record:
    description: "Handler for QM_RECORD_UPDATED event"
    post:
      body:
        application/json:
          type: string
      responses:
        204:
