#%RAML 1.0

title: Source Record Storage Module
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage API
    content: API for managing records

types:
  snapshot: !include raml-storage/schemas/mod-source-record-storage/snapshot.json
  snapshotCollection: !include raml-storage/schemas/mod-source-record-storage/snapshotCollection.json
  record: !include raml-storage/schemas/dto/record.json
  recordCollection: !include raml-storage/schemas/dto/recordCollection.json
  sourceRecord: !include raml-storage/schemas/dto/sourceRecord.json
  sourceRecordCollection: !include raml-storage/schemas/dto/sourceRecordCollection.json
  errors: !include raml-storage/raml-util/schemas/errors.schema
  recordModel: !include raml-storage/schemas/mod-source-record-storage/recordModel.json
  testMarcRecordsCollection: !include raml-storage/schemas/mod-source-record-storage/testMarcRecordsCollection.json

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml
  searchable: !include raml-storage/raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-storage/raml-util/rtypes/collection.raml
  collection-item: !include raml-storage/raml-util/rtypes/item-collection.raml

/source-storage:
  /snapshots:
    displayName: Snapshots
    description: API for managing Snapshots
    type:
      collection:
        schemaCollection: snapshotCollection
        schemaItem: snapshot
        exampleCollection: !include raml-storage/examples/mod-source-record-storage/snapshotCollection.sample
        exampleItem: !include raml-storage/examples/mod-source-record-storage/snapshot.sample
    post:
      is: [validate]
    get:
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example status=NEW",
          example:
            "status=NEW"
        },
        pageable,
        validate
      ]
    /{jobExecutionId}:
      displayName: Snapshot
      description: Get, Delete or Update a specific Snapshot
      type:
        collection-item:
          schema: snapshot
          exampleItem: !include raml-storage/examples/mod-source-record-storage/snapshot.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: snapshot
      delete:
        responses:
          204:
            body:
              text/plain: !!null
  /records:
    displayName: Records
    description: API for managing Records
    type:
      collection:
        schemaCollection: recordCollection
        schemaItem: record
        exampleCollection: !include raml-storage/examples/mod-source-record-storage/recordCollection.sample
        exampleItem: !include raml-storage/examples/mod-source-record-storage/record.sample
    post:
      is: [validate]
    get:
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example recordType=MARC",
          example:
            "recordType=MARC"
        },
        pageable,
        validate
      ]
    /{id}:
      displayName: Record
      description: Get, Delete or Update a specific Record
      type:
        collection-item:
          schema: record
          exampleItem: !include raml-storage/examples/mod-source-record-storage/record.sample
      put:
        is: [validate]
        responses:
          200:
            body:
              application/json:
                type: record
      delete:
        responses:
          204:
            body:
              text/plain: !!null
  /sourceRecords:
    displayName: Source Records
    description: API for getting Source Records
    get:
      description: Get a list of Source Records
      queryParameters:
        deleted:
          description: selection condition of sourceRecords by field 'deleted'
          example: false
          type: boolean
          default: false
          required: false
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example recordType=MARC",
          example:
            "recordType=MARC"
        },
        pageable,
        validate
      ]
      responses:
        200:
          body:
            application/json:
              type: sourceRecordCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /populate-test-marc-records:
    post:
      description: A non-production endpoint to populate MARC records for testing purposes. Available only in case "test.mode" environment variable is set to true
      is: [validate]
      body:
        application/json:
          type: testMarcRecordsCollection
      responses:
        204:
          body:
            text/plain: !!null
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /recordsCollection:
    post:
      description: "Create records from record collection"
      is: [validate]
      body:
        application/json:
          type: recordCollection
      responses:
        201:
          body:
            application/json:
              type: recordCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
