#%RAML 1.0

title: Source Record Storage Module
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Source Record Storage API
    content: API for managing records

types:
  snapshot: !include snapshot.json
  snapshotCollection: !include snapshotCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/source-storage:
  /snapshot:
    displayName: Snapshot
    description: API for managing Snapshots
    type:
      collection:
        schemaCollection: snapshotCollection
        schemaItem: snapshot
        exampleCollection: !include examples/snapshotCollection.sample
        exampleItem: !include examples/snapshot.sample
    get:
      description: Get a list of snapshots
      is: [
        searchable: {
          description:
            "with valid searchable fields: for example status=NEW",
          example:
            "status=NEW"
        },
        pageable,
        validate
      ]
      responses:
        200:
          body:
            application/json:
              type: snapshotCollection
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    post:
      description: "Create new snapshot"
      is: [validate]
      body:
        application/json:
          type: snapshot
      responses:
        201:
          body:
            application/json:
              type: snapshot
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{jobExecutionId}:
      get:
        description: Get snapshot by id
        responses:
          200:
            body:
              application/json:
                type: snapshot
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      put:
        description: Update snapshot
        body:
          application/json:
            type: snapshot
        responses:
          200:
            body:
              application/json:
                type: snapshot
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          422:
            description: "Unprocessable Entity"
            body:
              application/json:
                type: errors
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      delete:
        description: Delete snapshot by id
        responses:
          204:
            body:
              text/plain: !!null
          404:
            description: "File not found"
            body:
              text/plain:
                example: "File not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
